### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by chris18890**
hey @ramgarden & everyone else,

Great to see you're still doing dev work on Seltzer, I'd love to review & possibly pull your changes uptream; there's also been a lot of work done to Seltzer in the origin repo & they've diverged substantially now! Would you be interested in collaborating to merge in some of the differences?

All the best,

Chris 8-)

### CODE REVIEW

**Comment by ramgarden** [comment]
We switched from using Seltzer to our own home built version called Tonic.  :)
We can merge this if you want but it's not really used any more.
You can learn more about Tonic here: https://github.com/MelbourneMakerSpace/Tonic

**Comment by chris18890** [comment]
Ah, cool, not a problem, didn't know if you'd made the switch or not :) entirely up to you if you want to merge it or delete the repo if it's not being used any more :)

**Comment by chris18890** [comment]
Ah, cool, not a problem, didn't know if you'd made the switch or not :) entirely up to you if you want to merge it or delete the repo if it's not being used any more :)

**Comment by chris18890** [comment]
Ah, cool, not a problem, didn't know if you'd made the switch or not :) entirely up to you if you want to merge it or delete the repo if it's not being used any more :)

**Pull request closed without merging**
